net = RecurrentNetwork()
net.addInputModule(LinearLayer(2,name='input'))
net.addModule(SigmoidLayer (2,name='hidden'))
net.addModule(BiasUnit('bias'))
net.addOutputModule(SigmoidLayer (2,name='output'))
net.addModule(LinearLayer(2,name='context'))
net.addConnection(FullConnection(net['input'], net['hidden']))
net.addConnection(FullConnection(net['context'], net['hidden']))
net.addConnection(FullConnection(net['bias'], net['hidden']))
net.addConnection(FullConnection(net['bias'], net['output']))
net.addConnection(FullConnection(net['hidden'], net['output']))
net.addRecurrentConnection(FullConnection(net['hidden'], net['context']))
net.sortModules()
net.randomize()
net.reset()
